# Generated by Django 2.0 on 2019-08-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0002_auto_20190816_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='上传的文件', null=True, upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
